language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - mv tests/database_settings.yml.dist tests/database_settings.yml

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpspec run -fpretty

notifications:
    email: "chris@neoxygen.io"