language: php

php:
    - 5.4
    - 5.5
    - 5.6

install:
    - composer self-update
    - composer update --prefer-source --no-interaction

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpspec run -fpretty

notifications:
    email: "chris@neoxygen.io"